"""
Sample: iterative "write -> critique -> refine" pipeline using Google ADK's
LoopAgent, served over an HTTP API instead of asking an agent to invent its
own input.

LoopAgent is a workflow agent from the Google Agent Development Kit (ADK) that
runs its sub_agents repeatedly, in order, on every iteration until either:
  - `max_iterations` is reached, or
  - some sub-agent sets `actions.escalate = True` on its context, which the
    LoopAgent treats as a signal to stop.

Escalating can be done from a tool (`tool_context.actions.escalate = True`),
but this sample does it from an `after_agent_callback` on the CriticAgent
instead: the callback runs right after the critic produces its verdict, reads
that verdict straight out of session state, and escalates once every scored
criterion clears the approval threshold -- no dedicated "exit" tool or extra
LLM call required.

Pipeline (root_agent IS the LoopAgent -- no separate agent generates a
starting draft):
  TestCaseRefinementLoop (LoopAgent):
    a. WriterAgent  - on the first pass, drafts test cases straight from the
                       story's requirements/acceptance criteria; on later
                       passes, revises them per the critic's scoring feedback.
    b. CriticAgent  - scores the test cases against a fixed rubric (see
                       CRITERIA below), one score per criterion, as a JSON
                       array. Its after_agent_callback stops the loop once
                       every criterion scores at/above APPROVAL_SCORE_THRESHOLD.

The starting input -- a user story and its acceptance criteria -- comes from
an HTTP POST body instead of being generated by an LLM:

    POST /test-cases
    {
      "story": {
        "id": "US-142",
        "requirements": "As a ..., I want ..., so that ...\\n\\nAcceptance Criteria:\\n  AC-1: ..."
      },
      "session_id": "regie_123"
    }

Install:
    pip install google-adk fastapi uvicorn

Auth:
    Set GOOGLE_API_KEY (AI Studio) or configure Application Default
    Credentials for Vertex AI before running.

Run:
    python loop_agent_sample.py
    # then, from another shell:
    curl -X POST http://localhost:8000/test-cases -H "Content-Type: application/json" -d @request.json
"""

import json

from fastapi import FastAPI
from pydantic import BaseModel

from google.genai import types
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from uc001_requirements_evaluator.constants import RUBRIC_TABLE, StateKey
import uc001_requirements_evaluator.tools.bigquery_tools as bq
from uc001_requirements_evaluator.pipeline import build_pipeline
from uc001_requirements_evaluator.config import RUBRIC_VERSION

# The rubric the critic scores the test cases against, 1 (very poor) to
# 10 (excellent) per criterion. Edit this dict to change what gets scored --
# both the critic's instruction and the approval check below read from it.
CRITERIA = {
    "Coverage of Acceptance Criteria": "does every AC-# in the story have at least one test case?",
    "Clarity": "is each test case unambiguous about its steps and expected result?",
    "Testability": "can each test case be executed and verified objectively?",
    "Consistency": "do the test cases avoid contradicting each other or the story?",
}
APPROVAL_SCORE_THRESHOLD = 8

APP_NAME = "loop_agent_demo"


# def stop_loop_if_approved(callback_context: CallbackContext):
#     """after_agent_callback on CriticAgent: escalate once every criterion is approved.

#     `CallbackContext.actions` is the same `EventActions` object a tool would
#     get from `ToolContext.actions`. By the time this callback runs, the
#     critic's `output_key` write (the JSON scores array) has already landed
#     in state, so we can just parse it and decide whether to stop the loop --
#     no tool call, and no extra LLM turn, needed.
#     """
#     try:
#         scores = json.loads(callback_context.state.get(STATE_SCORES, ""))
#     except (TypeError, ValueError):
#         return  # critic didn't return valid JSON this pass; let the writer try again

#     if scores and all(entry.get("score", 0) >= APPROVAL_SCORE_THRESHOLD for entry in scores):
#         print(f"  [callback] {callback_context.agent_name} approved (all scores >= {APPROVAL_SCORE_THRESHOLD}) -> stopping loop")
#         callback_context.actions.escalate = True


# a. Runs inside the loop: writes the initial test cases from the story's
# requirements, or revises them per the critic's latest scoring feedback.
# writer_agent = LlmAgent(
#     name="WriterAgent",
#     model=MODEL,
#     instruction=f"""You are a QA engineer writing test cases for a user story.

# User story and acceptance criteria (state key '{STATE_REQUIREMENTS}'):
# {{{STATE_REQUIREMENTS}}}

# Previous scoring feedback, if any (state key '{STATE_SCORES}'):
# {{{STATE_SCORES}}}

# Existing test cases, if any (state key '{STATE_TEST_CASES}'):
# {{{STATE_TEST_CASES}}}

# If the scoring feedback above is empty, write an initial numbered list of
# concise test cases that together cover every acceptance criterion in the
# story.
# Otherwise, look at which criteria scored below {APPROVAL_SCORE_THRESHOLD}
# and revise the existing test cases to raise those scores, keeping whatever
# already works.
# Output ONLY the numbered list of test cases, nothing else.""",
#     description="Drafts test cases from the story, or revises them per scoring feedback.",
#     output_key=STATE_TEST_CASES,
# )

_criteria_bullets = "\n".join(f"  - {name}: {desc}" for name, desc in CRITERIA.items())
_criteria_example = ",\n  ".join(f'{{"criteria": "{name}", "score": <int 1-10>}}' for name in CRITERIA)

# b. Runs inside the loop: scores the test cases against the CRITERIA rubric.
# critic_agent = LlmAgent(
#     name="CriticAgent",
#     model=MODEL,
#     instruction=f"""You are a meticulous QA lead scoring test cases written for a user story.

# User story and acceptance criteria (state key '{STATE_REQUIREMENTS}'):
# {{{STATE_REQUIREMENTS}}}

# Test cases under review (state key '{STATE_TEST_CASES}'):
# {{{STATE_TEST_CASES}}}

# Score the test cases above against EACH of the following criteria, on a
# scale from 1 (very poor) to 10 (excellent):
# {_criteria_bullets}

# Output ONLY a JSON array with exactly one object per criterion above, in
# this shape and nothing else:
# [
#   {_criteria_example}
# ]""",
#     description="Scores the test cases against the CRITERIA rubric.",
#     output_key=STATE_SCORES,
#     after_agent_callback=stop_loop_if_approved,
# )

#   Build the main loop agent
root_agent = build_pipeline()
#   Create the session
session_service = InMemorySessionService()
runner = Runner(agent=root_agent, app_name=APP_NAME, session_service=session_service)

app = FastAPI(title="UC001")

class Story(BaseModel):
    id: str
    requirements: str


class GenerateTestCasesRequest(BaseModel):
    story: Story
    session_id: str


@app.post("/test-cases")
async def generate_test_cases(payload: GenerateTestCasesRequest):
    """Runs the refinement loop against the supplied story and returns the result."""
    user_id = payload.session_id
    session_id = payload.session_id
    rubric_version = {"version": RUBRIC_VERSION}
    rubric = bq.query_table(RUBRIC_TABLE,where=rubric_version,)

    session = await session_service.get_session(
        app_name=APP_NAME, user_id=user_id, session_id=session_id
    )
    if session is None:
        session = await session_service.create_session(
            app_name=APP_NAME,
            user_id=user_id,
            session_id=session_id,
            state={
                StateKey.STORY_ID: payload.story.id,
                StateKey.OPTIMIZER: payload.story.requirements,
                StateKey.EVALUATOR: "",
                StateKey.CRITERIA: rubric
            },
        )

    trigger_message = types.Content(
        role="user", parts=[types.Part(text="Generate the test cases.")]
    )

    async for _event in runner.run_async(
        user_id=user_id, session_id=session_id, new_message=trigger_message
    ):
        pass  # the result we care about lives in session state, not the events

    session = await session_service.get_session(
        app_name=APP_NAME, user_id=user_id, session_id=session_id
    )
    raw_scores = session.state.get(StateKey.EVALUATOR, "")
    try:
        scores = json.loads(raw_scores)
    except (TypeError, ValueError):
        scores = raw_scores  # critic didn't return valid JSON; pass the raw text through

    return {
        "story_id": session.state.get(StateKey.STORY_ID),
        "final_requirement": session.state.get(StateKey.OPTIMIZER),
        "test_cases": session.state.get(StateKey.EVALUATOR),
        "scores": scores,
    }


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8080)
