"""
Sample: iterative "write -> critique -> refine" pipeline using Google ADK's
LoopAgent, served over an HTTP API instead of asking an agent to invent its
own input.

LoopAgent is a workflow agent from the Google Agent Development Kit (ADK) that
runs its sub_agents repeatedly, in order, on every iteration until either:
  - `max_iterations` is reached, or
  - some sub-agent sets `actions.escalate = True` on its context, which the
    LoopAgent treats as a signal to stop.

Escalating can be done from a tool (`tool_context.actions.escalate = True`),
but this sample does it from an `after_agent_callback` on the CriticAgent
instead: the callback runs right after the critic produces its verdict, reads
that verdict straight out of session state, and escalates once every scored
criterion clears the approval threshold -- no dedicated "exit" tool or extra
LLM call required.

Pipeline (root_agent IS the LoopAgent -- no separate agent generates a
starting draft):
  TestCaseRefinementLoop (LoopAgent):
    a. WriterAgent  - on the first pass, drafts test cases straight from the
                       story's requirements/acceptance criteria; on later
                       passes, revises them per the critic's scoring feedback.
    b. CriticAgent  - scores the test cases against a fixed rubric (see
                       CRITERIA below), one score per criterion, as a JSON
                       array. Its after_agent_callback stops the loop once
                       every criterion scores at/above APPROVAL_SCORE_THRESHOLD.

The starting input -- a user story and its acceptance criteria -- comes from
an HTTP POST body instead of being generated by an LLM:

    POST /test-cases
    {
      "story": {
        "id": "US-142",
        "requirements": "As a ..., I want ..., so that ...\\n\\nAcceptance Criteria:\\n  AC-1: ..."
      },
      "session_id": "regie_123"
    }

Install:
    pip install google-adk "flask[async]"

Auth:
    Set GOOGLE_API_KEY (AI Studio) or configure Application Default
    Credentials for Vertex AI before running.

Run:
    python loop_agent_sample.py
    # then, from another shell:
    curl -X POST http://localhost:8000/test-cases -H "Content-Type: application/json" -d @request.json
"""

import json
import time
from typing import Optional

from flask import Flask, request
from pydantic import BaseModel

from google.genai import types
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from uc001_requirements_evaluator.constants import RUBRIC_TABLE, StateKey, SAMPLE_READABLE_CRITERIA, SAMPLE_REQUIREMENT
import uc001_requirements_evaluator.tools.bigquery_tools as bq
from uc001_requirements_evaluator.pipeline import build_pipeline
from uc001_requirements_evaluator.config import RUBRIC_VERSION
from uc001_requirements_evaluator.tools.jira_tools import get_jira_issue, add_jira_comment
from uc001_requirements_evaluator.tools.formatter import format_to_readable, clean_json_string
from uc001_requirements_evaluator.tools.bigquery_tools import insert_row
# The rubric the critic scores the test cases against, 1 (very poor) to
# 10 (excellent) per criterion. Edit this dict to change what gets scored --
# both the critic's instruction and the approval check below read from it.
CRITERIA = {
    "Coverage of Acceptance Criteria": "does every AC-# in the story have at least one test case?",
    "Clarity": "is each test case unambiguous about its steps and expected result?",
    "Testability": "can each test case be executed and verified objectively?",
    "Consistency": "do the test cases avoid contradicting each other or the story?",
}
APPROVAL_SCORE_THRESHOLD = 8

APP_NAME = "loop_agent_demo"

#   Build the main loop agent
root_agent = build_pipeline()
#   Create the session
session_service = InMemorySessionService()
runner = Runner(agent=root_agent, app_name=APP_NAME, session_service=session_service)

app = Flask("UC001")


async def _run_agent_timed(user_id: str, session_id: str, new_message) -> None:
    """Run the agent pipeline to completion, logging how long the whole run took."""
    start = time.perf_counter()
    async for _event in runner.run_async(
        user_id=user_id, session_id=session_id, new_message=new_message
    ):
        pass  # the result we care about lives in session state, not the events
    elapsed = time.perf_counter() - start
    print(f"Agent run took {elapsed:.2f} seconds")
    return elapsed

class Story(BaseModel):
    id: str
    requirements: Optional[str] = None


class GenerateTestCasesRequest(BaseModel):
    story: Story
    session_id: str


@app.route("/test-cases", methods=["POST"])
async def generate_test_cases():
    """Runs the refinement loop against the supplied story and returns the result."""
    payload = GenerateTestCasesRequest(**request.get_json())
    user_id = payload.session_id
    session_id = payload.session_id
    story_id = payload.story.id
    requirements = payload.story.requirements or get_jira_issue(story_id).get("description")
    query = {"version": RUBRIC_VERSION}
    rubric = bq.query_table(RUBRIC_TABLE,where=query)[0].get("dimensions")
    readable_rubric = format_to_readable(rubric)
    
    # ##   Static Input
    # requirements = SAMPLE_REQUIREMENT
    # readable_rubric = SAMPLE_READABLE_CRITERIA

    session = await session_service.get_session(
        app_name=APP_NAME, user_id=user_id, session_id=session_id
    )
    if session is None:
        session = await session_service.create_session(
            app_name=APP_NAME,
            user_id=user_id,
            session_id=session_id,
            state={
                StateKey.STORY_ID: payload.story.id,
                StateKey.OPTIMIZER: requirements,
                StateKey.EVALUATOR: {},
                StateKey.CRITERIA: readable_rubric
            },
        )

    trigger_message = types.Content(
        role="user", parts=[types.Part(text=requirements)]
    )

    run_time = await _run_agent_timed(user_id, session_id, trigger_message)

    session = await session_service.get_session(
        app_name=APP_NAME, user_id=user_id, session_id=session_id
    )
    scores = clean_json_string(session.state.get(StateKey.EVALUATOR, ""))

    # Create a comment on the JIRA ticket with the refined requirements
    add_jira_comment(story_id, session.state.get(StateKey.OPTIMIZER))

    row_entry = {
        "session_id": session_id,
        "story_id": story_id,
        "evaluation": scores,
        "result": session.state.get(StateKey.OPTIMIZER),
        "duration": int(run_time)
    }

    insert_row(row_entry, "results")

    return {
        "story_id": session.state.get(StateKey.STORY_ID),
        "final_requirement": session.state.get(StateKey.OPTIMIZER)
    }

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8080, debug=True)
